# @format

packages:
    - apps/*
    - packages/*

allowBuilds:
    bcrypt: true
    electron: true
    electron-winstaller: true
    esbuild: true
    sharp: true
    unrs-resolver: true

minimumReleaseAgeExclude:
    - framer-motion@13.0.0
    - motion-dom@13.0.0
    - motion-utils@13.0.0
    - lucide-react@1.30.0
