name: Shared Build Test

on:
    workflow_call:
    push:
    pull_request:

env:
    FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
    build-test:
        name: Workspace Build Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 24

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install deps
              run: pnpm install

            - name: Run Workspace Build
              run: pnpm build
